<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        DB::table('products')->insert([
            [
                'name' => 'Chocolate cake with cream.',
                'description' => 'The cake is made in two bowls, no mixer required, simple ingredients that you’ll already have in your kitchen and topped with the most incredible chocolate cream cheese frosting. It’s not too sweet, too rich, or too hard to make, just the most perfect homemade chocolate cake that you’ll make again and again and again!',
                'status' => 1,
                'price' => 40,
                'cate_id' => 2,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 1,
                'featured' => 1,

            ],
            [
                'name' => 'Vegetable soup',
                'description' => 'Not only is this soup delicious but and it’s so easy to make. It just takes some chopping and a bit of simmering until you’ve got a soup everyone will love!',
                'status' => 1,
                'price' => 55,
                'cate_id' => 12,
                'discount' => 35,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 1,
                'featured' => 0,

            ],
            [
                'name' => 'Beefsteak',
                'description' => 'This is just an excellent beef steak marinade that adds juiciness and flavour into steaks, transforming economical steaks from just ok to “wow!”. It injects extra flavour without overpowering the natural flavour of beef, and makes the meat tender.',
                'status' => 1,
                'price' => 60,
                'cate_id' => 8,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 1,
                'featured' => 0,

            ],
            [
                'name' => 'Vegetarian noodles',
                'description' => 'Taking cues from the ever-popular Roman dish cacio e pepe (cheese and pepper), this is a modern reworking of these classic umami flavours into a vibrant Asian-ish noodle dish. Spice and piquancy come from the freshly ground black pepper, which is teamed with just enough tongue-tingling Sichuan pepper to excite your taste buds. ',
                'status' => 1,
                'price' => 45,
                'cate_id' => 7,
                'discount' => 30,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 1,
                'featured' => 1,

            ],
            [
                'name' => 'Italian noodles',
                'description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam magni laborum fugiat corporis ipsum reprehenderit nisi unde, perspiciatis, similique ipsam pariatur dolores sapiente voluptas. Voluptatum minus dolores nam eligendi neque?',
                'status' => 1,
                'price' => 50,
                'cate_id' => 7,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 1,
                'featured' => 0,

            ],
            [
                'name' => 'Coffee cake',
                'description' => 'Coffee cake is one of those magical cakes that gets away with being acceptable to eat any time of the day.',
                'status' => 1,
                'price' => 40,
                'cate_id' => 2,
                'discount' => 35,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 1,
                'featured' => 1,

            ],
            [
                'name' => 'Cereals cake',
                'description' => 'The best part about Cereal Cake is you can make it with nearly any cereal you have. Denser, more fiber-rich cereals will give you a slightly denser cake than light rice-based cereals, but either way the cake is delicious.',
                'status' => 1,
                'price' => 75,
                'cate_id' => 2,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 1,
                'featured' => 0,
            ],
            [
                'name' => 'Roasted Chicken',
                'description' => 'This roast chicken recipe is proof that there’s really nothing simpler, more delicious, or more comforting than a beautifully browned roast bird surrounded by a puddle of buttery, garlicky pan juices.',
                'status' => 1,
                'price' => 75,
                'cate_id' => 8,
                'discount' => null,
                'tag' => null,
                'rating' => 3,
                'restaurant_id' => 1,
                'featured' => 0,
            ],
            [
                'name' => 'Chicken Soup',
                'description' => 'Classic chicken soup is exactly what you need, whether to soothe a cold or just to warm your bones. It should be flavorful yet clean, and satisfying without being overly rich or heavy.',
                'status' => 1,
                'price' => 80,
                'cate_id' => 12,
                'discount' => 65,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 1,
                'featured' => 0,
            ],
            [
                'name' => 'Homemade Creamy Vegetable Soup',
                'description' => 'Homemade Creamy Vegetable Soup is an insanely delicious, creamy vegetable soup without any cream. It’s perfect if you are looking for a vegetarian meal or just something light and easy.',
                'status' => 1,
                'price' => 75,
                'cate_id' => 12,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 1,
                'featured' => 1,
            ],
            [
                'name' => 'Chocolate Cake With Chocolate Buttercream',
                'description' => 'A dense, rich, ultra-chocolatey cake, similar to devil\'s food cake, frosted with a fluffy chocolate ...',
                'status' => 1,
                'price' => 75,
                'cate_id' => 2,
                'discount' => 50,
                'tag' => null,
                'rating' => 3,
                'restaurant_id' => 2,
                'featured' => 1,
            ],
            [
                'name' => 'Ultimate Birthday Cake From \'Baked Occasions\'',
                'description' => 'Three layers of densely spongy "very vanilla" cake are enveloped in layers of bright white frosting and coated with rainbow sprinkles. Cutting into the cake reveals more sprinkles, folded into the cake batter. The effect is childlike and utterly charming, with the innocent sweetness of vanilla providing the perfect backdrop.',
                'status' => 1,
                'price' => 60,
                'cate_id' => 2,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 2,
                'featured' => 1,
            ],
            [
                'name' => 'Moist Vanilla Cake Recipe With Easy Buttercream',
                'description' => 'This vanilla cake recipe has an amazing flavor, a soft, cloud-like crumb, and is so incredibly moist. Using cake flour, the reverse creaming method, lots of butter, and a touch of oil keeps this cake moist for days.',
                'status' => 1,
                'price' => 55,
                'cate_id' => 2,
                'discount' => 45,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 2,
                'featured' => 1,
            ],
            [
                'name' => 'Cappuccino Coffee',
                'description' => 'A cappuccino is an Italian coffee drink that is traditionally prepared with equal parts double espresso, steamed milk, and steamed milk foam on top. Cream may be used instead of milk. It is typically smaller in volume than a latte, and has a thicker layer of microfoam.',
                'status' => 1,
                'price' => 25,
                'cate_id' => 4,
                'discount' => 20,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 2,
                'featured' => 0,
            ],
            [
                'name' => 'Espresso',
                'description' => 'An original Espresso cup starts with quality Arabica beans, mixed with a balanced proportion of Robusta beans, giving a caramel sweetness, a mild sour taste and a thick consistency. To achieve this combination, we grind the coffee beans fresh for each brew.',
                'status' => 1,
                'price' => 20,
                'cate_id' => 4,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 2,
                'featured' => 0,
            ],
            [
                'name' => 'Americano Coffee',
                'description' => 'The americano way of making coffee is one of the most famous and popular ways to prepare coffee in the world. Americano coffee is well known in America and Western countries.',
                'status' => 1,
                'price' => 20,
                'cate_id' => 4,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 2,
                'featured' => 1,
            ],
            [
                'name' => 'Black Tea',
                'description' => 'Black tea may have similar benefits to green tea. However, many studies have looked specifically at black tea, and how the oxidation process may impact health. A key area of interest is black tea as a source of antioxidants. Antioxidants help combat free radicals. Free radicals are unstable molecules in the body that result from both natural processes and environmental pressures. The body can remove free radicals, but if too many build up, they can damage or change cells in the body.',
                'status' => 1,
                'price' => 15,
                'cate_id' => 6,
                'discount' => 12,
                'tag' => null,
                'rating' => 2,
                'restaurant_id' => 2,
                'featured' => 0,
            ],
            [
                'name' => 'Bubble Milk Tea',
                'description' => 'If you’re looking at the picture of my bubble tea, you’ll see that there’s a layer of pearls on the bottom. These ‘pearls’ are typical for bubble tea. You might wonder what the bubbles are made of. They’re tapioca pearls (sometimes called tapioca balls). Tapioca is a starch extracted from the Cassava plant. You can create your own Tapioca balls from Tapioca starch (Tapioca Zetmeel in Dutch), but you can also buy Tapioca Balls.',
                'status' => 1,
                'price' => 15,
                'cate_id' => 6,
                'discount' => 12,
                'tag' => null,
                'rating' => 2,
                'restaurant_id' => 2,
                'featured' => 1,
            ],
            [
                'name' => 'Thai Tea Boba',
                'description' => 'The short answer is that boba tea is a mix of Thai tea and bubble tea and it’s most definitely becoming a popular drink. Boba tea is unique because of the ‘boba’ that sink to the bottom of the drink. These boba are partially cooked tapioca flour with a chewy texture and a naturally gluten-free and flavor-free makeup.',
                'status' => 1,
                'price' => 15,
                'cate_id' => 6,
                'discount' => 10,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 2,
                'featured' => 1,
            ],
            [
                'name' => 'Iced Tea',
                'description' => 'Whether you’re looking for a drink to round out your summer BBQ with Juicy Burgers and Grilled Corn on the Cob, or just want to have some quick caffeine on hand throughout the day, you’ll love this iced tea.',
                'status' => 1,
                'price' => 10,
                'cate_id' => 6,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 2,
                'featured' => 1,
            ],
            [
                'name' => 'Flavorful Street Food',
                'description' => 'The price includes entrance fees, motorbikes, food and drinks. The price is subject to change due to Vietnam’s public holidays. You may contact us for further details. The minimum group size is 2 people.',
                'status' => 1,
                'price' => 72,
                'cate_id' => 5,
                'discount' => 60,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 3,
                'featured' => 1,
            ],
            [
                'name' => 'Vietnamese Grilled Meat Vermicelli',
                'description' => 'It is basically a warm broth with minced pork and Vietnamese traditional noodle. You’ll be served by a plate of rice noodles, fresh herbs, and a bowl of warm broth with grilled minced pork. The broth and the pork are the ones making this dish unique. When eating, you will dip rice noodles into the broth, even grilled pork if you like and eat them like western soups.',
                'status' => 1,
                'price' => 25,
                'cate_id' => 5,
                'discount' => 22,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 3,
                'featured' => 0,
            ],
            [
                'name' => 'Combo meal 1',
                'description' => 'If you love to eat out, especially fast food. About a third of household food budgets are spent on food prepared outside the home, with most of us consuming it on average two or three times a week.',
                'status' => 1,
                'price' => 100,
                'cate_id' => 1,
                'discount' => 89,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 3,
                'featured' => 1,
            ],
            [
                'name' => 'The Best Roast Chicken',
                'description' => 'This recipe uses very simple ingredients that you probably already have in your pantry. If not, you’ll be able to find them easily and cheap at your local grocery store. With only 5 ingredients paired with a tried and true method, you’ll be a chicken roasting master with your very first stab at this recipe.',
                'status' => 1,
                'price' => 105,
                'cate_id' => 8,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 3,
                'featured' => 1,
            ],
            [
                'name' => 'Spit-Roasted Duck with Orange and Rosemary',
                'description' => 'If you’ve only had oven-roasted duck, this recipe just may change your whole opinion of the bird. It comes out so crisp and delicious, with a deeply brown, burnished skin, it’s almost like Chinese roast duck.',
                'status' => 1,
                'price' => 97,
                'cate_id' => 8,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 3,
                'featured' => 1,
            ],
            [
                'name' => 'Gado-gado',
                'description' => 'It’s a colourful salad featuring a mix of vegetables, including potatoes, long beans, bean sprouts, spinach, corn and cabbage, and a side of peanut sauce. You can also add tofu, tempeh and hard-boiled eggs.',
                'status' => 1,
                'price' => 40,
                'cate_id' => 3,
                'discount' => 35,
                'tag' => null,
                'rating' => 3,
                'restaurant_id' => 4,
                'featured' => 1,
            ],
            [
                'name' => 'Mi Quang (Mì Quảng)',
                'description' => 'Mì quảng is a tasty turmeric-noodle dish brimming with typical Vietnamese veggies, such as water mint, basil, coriander, sliced banana flower and lettuce. There are many variations of mì quảng, and some include pork, chicken, beef, shrimp or fish. However, a vegetarian option is almost always on the menu.',
                'status' => 1,
                'price' => 35,
                'cate_id' => 3,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 4,
                'featured' => 0,
            ],
            [
                'name' => 'Edamame',
                'description' => 'Today, edamame is a well-known dish shared as an appetiser around the world. We all need to give thanks to the Japanese for coming up with this tasty combination of steamed young soybeans topped with sea salt.',
                'status' => 1,
                'price' => 45,
                'cate_id' => 3,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 4,
                'featured' => 0,
            ],
            [
                'name' => 'Moon Cake',
                'description' => 'This intricate and dense cake is a Chinese tradition to bring good luck. The ingredients are available only at specialty stores, and the process is a bit tricky, so most people buy the cakes. The good news: Because they are so dense, a small one yields a lot of servings.',
                'status' => 1,
                'price' => 35,
                'cate_id' => 9,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 4,
                'featured' => 1,
            ],
            [
                'name' => 'Croissant',
                'description' => 'This famous French pastry is loaded with rich butter to make a flaky and crisp outer layer with a soft inside. Good ones usually cost a few dollars from bakeries, which is a small price to pay to avoid the process of layering the dough with butter, or at least from seeing how much butter goes into each one.',
                'status' => 1,
                'price' => 30,
                'cate_id' => 9,
                'discount' => null,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 4,
                'featured' => 0,
            ],
            [
                'name' => 'Wheat Beer',
                'description' => 'Currently, the Wheat Beer line has many different varieties, but the oldest and most popular is German-style Bavarian Weizen.',
                'status' => 1,
                'price' => 45,
                'cate_id' => 10,
                'discount' => 30,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 5,
                'featured' => 0,
            ],
            [
                'name' => 'Thai beer',
                'description' => 'The taste of this lager beer really makes the drinker completely conquered. The beer is fragrant, smooth, outstanding with the aroma of barley with a light sweet aftertaste... All creating an attractive and interesting highlight.',
                'status' => 1,
                'price' => 30,
                'cate_id' => 10,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 5,
                'featured' => 0,
            ],
            [
                'name' => 'Stinky Tofu',
                'description' => 'The name kind of says it all: Stinky tofu is fermented tofu with a strong odor (and it’s said that the stronger it smells, the better it tastes). Tofu is brined in a mixture of fermented milk, vegetables, meat and aromatics before fermenting for up to several months—kind of like cheese. Its preparation depends on the region, but it can be served cold, steamed, stewed or deep-fried with chile and soy sauces on the side.',
                'status' => 1,
                'price' => 50,
                'cate_id' => 11,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 5,
                'featured' => 1,
            ],
            [
                'name' => 'Scallion Pancakes',
                'description' => 'No maple syrup here: These savory pancakes are more like a supremely chewy flatbread with bits of scallion and oil mixed throughout the dough. They’re served as street food, in restaurants and fresh or frozen in supermarkets, and since they’re pan-fried, they have the ideal balance of crispy edges and soft insides.',
                'status' => 1,
                'price' => 40,
                'cate_id' => 11,
                'discount' => null,
                'tag' => null,
                'rating' => 4,
                'restaurant_id' => 5,
                'featured' => 0,
            ],
            [
                'name' => 'Kung Pao Chicken',
                'description' => 'The spicy stir-fried chicken dish originates from the Sichuan province of southwestern China, and while you’ve probably had the Westernized version, the real thing is fragrant, spicy and a little bit mouth-numbing, thanks to Sichuan peppercorns. If you want to avoid the gloppy version you get here in the United States, Yinn Low says its actually quite easy to re-create at home.',
                'status' => 1,
                'price' => 90,
                'cate_id' => 11,
                'discount' => 85,
                'tag' => null,
                'rating' => 5,
                'restaurant_id' => 5,
                'featured' => 1,
            ],
        ]);
        DB::table('product_images')->insert([
            [
                'product_id' => '1',
                'path' => 'chocolate-cake-with-cream-0.jpg',
            ],
            [
                'product_id' => '1',
                'path' => 'chocolate-cake-with-cream-1.jpg',
            ],
            [
                'product_id' => '1',
                'path' => 'chocolate-cake-with-cream-2.jpg',
            ],
            [
                'product_id' => '2',
                'path' => 'vegetable-soup-1.jpg',
            ],
            [
                'product_id' => '2',
                'path' => 'vegetable-soup-2.jpg',
            ],
            [
                'product_id' => '2',
                'path' => 'vegetable-soup-3.jpg',
            ],
            [
                'product_id' => '3',
                'path' => 'beef-steak-3.jpg',
            ],
            [
                'product_id' => '3',
                'path' => 'beef-steak-1.jpg',
            ],
            [
                'product_id' => '3',
                'path' => 'beef-steak-2.jpg',
            ],
            [
                'product_id' => '4',
                'path' => 'restaurant-detail-big-img1-3.jpg',
            ],
            [
                'product_id' => '4',
                'path' => 'vegetarian-noodle-2.jpg',
            ],
            [
                'product_id' => '4',
                'path' => 'vegetarian-noodle-3.jpg',
            ],
            [
                'product_id' => '5',
                'path' => 'italian-noodle-1.jpg',
            ],
            [
                'product_id' => '5',
                'path' => 'italian-noodle-2.jpg',
            ],
            [
                'product_id' => '5',
                'path' => 'italian-noodle-3.jpg',
            ],
            [
                'product_id' => '6',
                'path' => 'coffee-cake-1.jpg',
            ],
            [
                'product_id' => '6',
                'path' => 'coffee-cake-2.jpeg',
            ],
            [
                'product_id' => '6',
                'path' => 'coffee-cake-3.jpg',
            ],
            [
                'product_id' => '7',
                'path' => 'gallery-inner-img1-3.jpg',
            ],
            [
                'product_id' => '8',
                'path' => 'roasted-chicken.jpg',
            ],
            [
                'product_id' => '9',
                'path' => 'chicken-soup.jpg',
            ],
            [
                'product_id' => '10',
                'path' => 'creamy-vegetable-soup.jpg',
            ],
            [
                'product_id' => '11',
                'path' => 'cake.jpg',
            ],
            [
                'product_id' => '12',
                'path' => 'birthday-cake.jpg',
            ],
            [
                'product_id' => '13',
                'path' => 'moist_vanilla_cake.jpg',
            ],
            [
                'product_id' => '14',
                'path' => 'cappucino.jpg',
            ],
            [
                'product_id' => '15',
                'path' => 'espresso.jpg',
            ],
            [
                'product_id' => '16',
                'path' => 'americano.jpg',
            ],
            [
                'product_id' => '17',
                'path' => 'black-tea.jpg',
            ],
            [
                'product_id' => '18',
                'path' => 'recipe-bubble-tea.jpg',
            ],
            [
                'product_id' => '19',
                'path' => 'thai-tea-boba.jpg',
            ],
            [
                'product_id' => '20',
                'path' => 'iced-tea.jpg',
            ],
            [
                'product_id' => '21',
                'path' => 'xien-que.jpeg',
            ],
            [
                'product_id' => '22',
                'path' => 'Bun-Cha-Vietnamese.jpg',
            ],
            [
                'product_id' => '23',
                'path' => 'fast-food.jpg',
            ],
            [
                'product_id' => '24',
                'path' => 'roast-chicken-1.jpg',
            ],
            [
                'product_id' => '25',
                'path' => 'spit-roasted-duck.jpg',
            ],
            [
                'product_id' => '26',
                'path' => 'gado-gado.jpg',
            ],
            [
                'product_id' => '27',
                'path' => 'mi-quang.jpg',
            ],
            [
                'product_id' => '28',
                'path' => 'edamame.jpg',
            ],
            [
                'product_id' => '29',
                'path' => 'moon-cake.jpg',
            ],
            [
                'product_id' => '30',
                'path' => 'croissant.jpg',
            ],
            [
                'product_id' => '31',
                'path' => 'wheat-beer.jpg',
            ],
            [
                'product_id' => '32',
                'path' => 'thai-beer.jpg',
            ],
            [
                'product_id' => '33',
                'path' => 'traditional-chinese-food-stinky-tofu.jpg',
            ],
            [
                'product_id' => '34',
                'path' => 'traditional-chinese-food-scallion-pancakes.jpg',
            ],
            [
                'product_id' => '35',
                'path' => 'traditional-chinese-food-kung-pao-chicken.jpg',
            ],
        ]);
        DB::table('categories')->insert([
            [
                'id' => 1,
                'cate_name' => 'Fast Food',
            ],
            [
                'id' => 2,
                'cate_name' => 'Cake',
            ],
            [
                'id' => 3,
                'cate_name' => 'Vegetarian',
            ],
            [
                'id' => 4,
                'cate_name' => 'Coffee/Dessert',
            ],
            [
                'id' => 5,
                'cate_name' => 'Street Food',
            ],
            [
                'id' => 6,
                'cate_name' => 'Tea',
            ],
            [
                'id' => 7,
                'cate_name' => 'Noodles',
            ],
            [
                'id' => 8,
                'cate_name' => 'Roasted Food',
            ],
            [
                'id' => 9,
                'cate_name' => 'Bakery',
            ],
            [
                'id' => 10,
                'cate_name' => 'Beer',
            ],
            [
                'id' => 11,
                'cate_name' => 'Chinese Food',
            ],
            [
                'id' => 12,
                'cate_name' => 'Soup',
            ],

        ]);
        DB::table('restaurants')->insert([
            [
                'restaurant_name' => 'King Saber',
                'address' => '108 Cau Giay, Cau Giay, Hanoi',
                'business_license' => 'business-license.png',
                'telephone' => '0123456789',
                'email' => 'demorestaurant@gmail.com',
                'owner_name' => 'Harry Kain',
                'avatar' => 'restaurant-logo1-2.png',
                'tel_owner' => '0123456789',
                'status' => '3',
                'user_id' => 1,
                'rating' =>5,
                'package' => 12,
                'start_date' => '2021-08-20',
                'end_date' => '2022-08-20'
            ],
            [
                'restaurant_name' => 'King Cafe',
                'address' => '98 Xuan Thuy, Cau Giay, Hanoi',
                'business_license' => 'business-license.png',
                'telephone' => '0312812312',
                'email' => 'demorestaurant@gmail.com',
                'owner_name' => 'Marry Cue',
                'avatar' => 'top-restaurant3.png',
                'tel_owner' => '0123421789',
                'status' => '3',
                'user_id' => 2,
                'rating' =>5,
                'package' => 12,
                'start_date' => '2021-08-20',
                'end_date' => '2022-08-20'
            ],
            [
                'restaurant_name' => 'Friend Zone',
                'address' => '29 Dich Vong, Cau Giay, Hanoi',
                'business_license' => 'business-license.png',
                'telephone' => '0312811231',
                'email' => 'demorestaurant@gmail.com',
                'owner_name' => 'Peter Pan',
                'avatar' => 'top-restaurant1.png',
                'tel_owner' => '0123223489',
                'status' => '3',
                'user_id' => 3,
                'rating' =>5,
                'package' => 12,
                'start_date' => '2021-08-20',
                'end_date' => '2022-08-20'
            ],
            [
                'restaurant_name' => 'Vegan World',
                'address' => '29 Thanh Thai, Cau Giay, Hanoi',
                'business_license' => 'business-license.png',
                'telephone' => '0312812311',
                'email' => 'veganworld@gmail.com',
                'owner_name' => 'John Smith',
                'avatar' => 'top-restaurant6.png',
                'tel_owner' => '0123314489',
                'status' => '3',
                'user_id' => 4,
                'rating' =>4,
                'package' => 12,
                'start_date' => '2021-08-20',
                'end_date' => '2022-08-20'
            ],
            [
                'restaurant_name' => 'Chinese Cuisine',
                'address' => '29 Ton That Thuyet, Nam Tu liem, Hanoi',
                'business_license' => 'business-license.png',
                'telephone' => '031242311',
                'email' => 'chinesecuisine@gmail.com',
                'owner_name' => 'John Smith',
                'avatar' => 'top-restaurant4.png',
                'tel_owner' => '0123114489',
                'status' => '3',
                'user_id' => 5,
                'rating' =>4,
                'package' => 12,
                'start_date' => '2021-08-20',
                'end_date' => '2022-08-20'
            ],
        ]);
        DB::table('restaurant_menu')->insert([
            [
                'restaurant_id' => '1',
                'cate_id' => '2',
            ],
            [
                'restaurant_id' => '1',
                'cate_id' => '12',
            ],
            [
                'restaurant_id' => '1',
                'cate_id' => '8',
            ],
            [
                'restaurant_id' => '1',
                'cate_id' => '7',
            ],
            [
                'restaurant_id' => '2',
                'cate_id' => '6',
            ],
            [
                'restaurant_id' => '2',
                'cate_id' => '2',
            ],
            [
                'restaurant_id' => '2',
                'cate_id' => '4',
            ],
            [
                'restaurant_id' => '3',
                'cate_id' => '1',
            ],
            [
                'restaurant_id' => '3',
                'cate_id' => '5',
            ],
            [
                'restaurant_id' => '3',
                'cate_id' => '8',
            ],
            [
                'restaurant_id' => '4',
                'cate_id' => '3',
            ],
            [
                'restaurant_id' => '4',
                'cate_id' => '9',
            ],
            [
                'restaurant_id' => '5',
                'cate_id' => '10',
            ],
            [
                'restaurant_id' => '5',
                'cate_id' => '11',
            ],
        ]);
        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('admin123'),
                'role' => 0,
                'restaurant_id' => null,
            ],
            [
                'name' => 'Sam Smith',
                'email' => 'restaurant1@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 2,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Nguyen Van A',
                'email' => 'restaurant2@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 2,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Nguyen Van B',
                'email' => 'restaurant3@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 2,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Nguyen Van C',
                'email' => 'restaurant4@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 2,
                'restaurant_id' => 4,
            ],
            [
                'name' => 'Nguyen Van D',
                'email' => 'restaurant5@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 2,
                'restaurant_id' => 5,
            ],
            [
                'name' => 'John Cena',
                'email' => 'customer1@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 1,
                'restaurant_id' => null,
            ],
            [
                'name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 1,
                'restaurant_id' => null,
            ],
            [
                'name' => 'John Wick',
                'email' => 'customer3@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 1,
                'restaurant_id' => null,
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'customer4@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 1,
                'restaurant_id' => null,
            ],
            [
                'name' => 'Bob Smith',
                'email' => 'customer5@gmail.com',
                'password' => Hash::make('12345678'),
                'role' => 1,
                'restaurant_id' => null,
            ],
        ]);
        DB::table('restaurant_images')->insert([
            [
                'restaurant_id' => '1',
                'path' => 'chicken-soup.jpg',
            ],
            [
                'restaurant_id' => '1',
                'path' => 'roast-chicken-1.jpg',
            ],
            [
                'restaurant_id' => '1',
                'path' => 'restaurant-detail-big-img1-3.jpg',
            ],
            [
                'restaurant_id' => '2',
                'path' => 'birthday-cake.jpg',
            ],
            [
                'restaurant_id' => '2',
                'path' => 'espresso.jpg',
            ],
            [
                'restaurant_id' => '2',
                'path' => 'thai-tea-boba.jpg',
            ],
            [
                'restaurant_id' => '2',
                'path' => 'iced-tea.jpg',
            ],
            [
                'restaurant_id' => '3',
                'path' => 'spit-roasted-duck.jpg',
            ],
            [
                'restaurant_id' => '3',
                'path' => 'Bun-Cha-Vietnamese.jpg',
            ],
            [
                'restaurant_id' => '3',
                'path' => 'xien-que.jpeg',
            ],
            [
                'restaurant_id' => '4',
                'path' => 'gado-gado.jpg',
            ],
            [
                'restaurant_id' => '4',
                'path' => 'mi-quang.jpg',
            ],
            [
                'restaurant_id' => '4',
                'path' => 'croissant.jpg',
            ],
            [
                'restaurant_id' => '5',
                'path' => 'wheat-beer.jpg',
            ],
            [
                'restaurant_id' => '5',
                'path' => 'thai-beer.jpg',
            ],
            [
                'restaurant_id' => '5',
                'path' => 'traditional-chinese-food-stinky-tofu.jpg',
            ],
        ]);

        DB::table('comments')->insert([
            [
                'product_id' => '1',
                'user_id' => 7,
                'email' => 'customer1@gmail.com',
                'name' => 'John Cena',
                'messages' => 'I love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '2',
                'user_id' => 7,
                'email' => 'customer1@gmail.com',
                'name' => 'John Cena',
                'messages' => 'I love this food!',
                'rating' => '4',
            ],
            [
                'product_id' => '3',
                'user_id' => 7,
                'email' => 'customer1@gmail.com',
                'name' => 'John Cena',
                'messages' => 'The food is great!',
                'rating' => '5',
            ],
            [
                'product_id' => '4',
                'user_id' => 7,
                'email' => 'customer1@gmail.com',
                'name' => 'John Cena',
                'messages' => 'I love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '5',
                'user_id' => 7,
                'email' => 'customer1@gmail.com',
                'name' => 'John Cena',
                'messages' => 'I love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '6',
                'user_id' => 7,
                'email' => 'customer1@gmail.com',
                'name' => 'John Cena',
                'messages' => 'I love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '7',
                'user_id' => 7,
                'email' => 'customer1@gmail.com',
                'name' => 'John Cena',
                'messages' => 'I love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '8',
                'user_id' => 8,
                'email' => 'customer2@gmail.com',
                'name' => 'Halley Quine',
                'messages' => 'The food is good but delivery really takes time.',
                'rating' => '3',
            ],
            [
                'product_id' => '9',
                'user_id' => 8,
                'email' => 'customer2@gmail.com',
                'name' => 'Halley Quine',
                'messages' => 'The food is good !',
                'rating' => '4',
            ],
            [
                'product_id' => '10',
                'user_id' => 8,
                'email' => 'customer2@gmail.com',
                'name' => 'Halley Quine',
                'messages' => 'I love it!',
                'rating' => '5',
            ],
            [
                'product_id' => '11',
                'user_id' => 8,
                'email' => 'customer2@gmail.com',
                'name' => 'Halley Quine',
                'messages' => 'The food is good but delivery is really time-consuming.',
                'rating' => '3',
            ],
            [
                'product_id' => '12',
                'user_id' => 8,
                'email' => 'customer2@gmail.com',
                'name' => 'Halley Quine',
                'messages' => 'The food is great !',
                'rating' => '4',
            ],
            [
                'product_id' => '13',
                'user_id' => 8,
                'email' => 'customer2@gmail.com',
                'name' => 'Halley Quine',
                'messages' => 'I really recommend this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '14',
                'user_id' => 8,
                'email' => 'customer2@gmail.com',
                'name' => 'Halley Quine',
                'messages' => 'I really recommend this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '15',
                'user_id' => 9,
                'email' => 'customer3@gmail.com',
                'name' => 'John Wick',
                'messages' => 'I really love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '16',
                'user_id' => 9,
                'email' => 'customer3@gmail.com',
                'name' => 'John Wick',
                'messages' => 'I like this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '17',
                'user_id' => 9,
                'email' => 'customer3@gmail.com',
                'name' => 'John Wick',
                'messages' => 'The food does not look like the same to its images!',
                'rating' => '2',
            ],
            [
                'product_id' => '18',
                'user_id' => 9,
                'email' => 'customer3@gmail.com',
                'name' => 'John Wick',
                'messages' => 'The food does not look like the same to its images!',
                'rating' => '2',
            ],
            [
                'product_id' => '19',
                'user_id' => 9,
                'email' => 'customer3@gmail.com',
                'name' => 'John Wick',
                'messages' => 'The food is really tasty!',
                'rating' => '4',
            ],
            [
                'product_id' => '20',
                'user_id' => 9,
                'email' => 'customer3@gmail.com',
                'name' => 'John Wick',
                'messages' => 'The food is really tasty!',
                'rating' => '4',
            ],
            [
                'product_id' => '21',
                'user_id' => 9,
                'email' => 'customer3@gmail.com',
                'name' => 'John Wick',
                'messages' => 'The food is really tasty!',
                'rating' => '4',
            ],
            [
                'product_id' => '22',
                'user_id' => 10,
                'email' => 'customer4@gmail.com',
                'name' => 'Michael Chen',
                'messages' => 'The food is really tasty!',
                'rating' => '4',
            ],
            [
                'product_id' => '23',
                'user_id' => 10,
                'email' => 'customer4@gmail.com',
                'name' => 'Michael Chen',
                'messages' => 'I really recommend this food!',
                'rating' => '4',
            ],
            [
                'product_id' => '24',
                'user_id' => 10,
                'email' => 'customer4@gmail.com',
                'name' => 'Michael Chen',
                'messages' => 'I love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '25',
                'user_id' => 10,
                'email' => 'customer4@gmail.com',
                'name' => 'Michael Chen',
                'messages' => 'The food is great!',
                'rating' => '5',
            ],
            [
                'product_id' => '26',
                'user_id' => 10,
                'email' => 'customer4@gmail.com',
                'name' => 'Michael Chen',
                'messages' => 'The food is great but delivery is not on time.',
                'rating' => '3',
            ],
            [
                'product_id' => '27',
                'user_id' => 10,
                'email' => 'customer4@gmail.com',
                'name' => 'Michael Chen',
                'messages' => 'The food tastes good!',
                'rating' => '4',
            ],
            [
                'product_id' => '28',
                'user_id' => 10,
                'email' => 'customer4@gmail.com',
                'name' => 'Michael Chen',
                'messages' => 'The food tastes good!',
                'rating' => '4',
            ],
            [
                'product_id' => '29',
                'user_id' => 11,
                'email' => 'customer5@gmail.com',
                'name' => 'Bob Smith',
                'messages' => 'The food tastes good!',
                'rating' => '4',
            ],
            [
                'product_id' => '30',
                'user_id' => 11,
                'email' => 'customer5@gmail.com',
                'name' => 'Bob Smith',
                'messages' => 'I love this food!',
                'rating' => '5',
            ],
            [
                'product_id' => '31',
                'user_id' => 11,
                'email' => 'customer5@gmail.com',
                'name' => 'Bob Smith',
                'messages' => 'I love this food!',
                'rating' => '4',
            ],
            [
                'product_id' => '32',
                'user_id' => 11,
                'email' => 'customer5@gmail.com',
                'name' => 'Bob Smith',
                'messages' => 'I really recommend this food!',
                'rating' => '4',
            ],
            [
                'product_id' => '33',
                'user_id' => 11,
                'email' => 'customer5@gmail.com',
                'name' => 'Bob Smith',
                'messages' => 'It tastes great!',
                'rating' => '4',
            ],
            [
                'product_id' => '34',
                'user_id' => 11,
                'email' => 'customer5@gmail.com',
                'name' => 'Bob Smith',
                'messages' => 'It tastes great!',
                'rating' => '4',
            ],
            [
                'product_id' => '35',
                'user_id' => 11,
                'email' => 'customer5@gmail.com',
                'name' => 'Bob Smith',
                'messages' => 'It is really delicious!',
                'rating' => '5',
            ],
        ]);

        DB::table('restaurant_reviews')->insert([
            [
                'restaurant_id' => 1,
                'user_id' => 7,
                'messages' => 'The food of restaurant is really tasty!',
                'rate' => 5,
            ],
            [
                'restaurant_id' => 2,
                'user_id' => 8,
                'messages' => 'The drinks is really tasty!',
                'rate' => 5,
            ],
            [
                'restaurant_id' => 3,
                'user_id' => 9,
                'messages' => 'The food of restaurant is really good, I go to Friend Zone with my friends every weekends!',
                'rate' => 5,
            ],
            [
                'restaurant_id' => 4,
                'user_id' => 10,
                'messages' => 'The food of restaurant is really good.',
                'rate' => 4,
            ],
            [
                'restaurant_id' => 5,
                'user_id' => 11,
                'messages' => 'The food of restaurant is really good.',
                'rate' => 4,
            ],

        ]);

        DB::table('orders')->insert([
            [
                'full_name' => 'John Cena',
                'email' => 'customer1@gmail.com',
                'phone' => '0123456789',
                'address' => 'Dich Vong, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '7',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-01-16 12:30:00',
                'delivered_time' => '2021-01-16 10:16:22',
                'total' => 400,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-01-16 10:15:33',
            ],
            [
                'full_name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'phone' => '0123456789',
                'address' => 'Thanh Thai, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '8',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-02-16 12:30:00',
                'delivered_time' => '2021-02-16 10:16:22',
                'total' => 350,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-02-16 10:15:33',
            ],
            [
                'full_name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'phone' => '0123456789',
                'address' => 'Thanh Thai, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '8',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-03-16 12:30:00',
                'delivered_time' => '2021-03-16 10:16:22',
                'total' => 450,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-03-16 10:15:33',
            ],
            [
                'full_name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'phone' => '0123456789',
                'address' => 'Thanh Thai, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '8',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-04-16 12:30:00',
                'delivered_time' => '2021-04-16 10:16:22',
                'total' => 500,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-04-16 10:15:33',
            ],
            [
                'full_name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'phone' => '0123456789',
                'address' => 'Thanh Thai, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '8',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-05-16 12:30:00',
                'delivered_time' => '2021-05-16 10:16:22',
                'total' => 525,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-05-16 10:15:33',
            ],
            [
                'full_name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'phone' => '0123456789',
                'address' => 'Thanh Thai, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '8',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-06-16 12:30:00',
                'delivered_time' => '2021-06-16 10:16:22',
                'total' => 600,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-06-16 10:15:33',
            ],
            [
                'full_name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'phone' => '0123456789',
                'address' => 'Thanh Thai, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '8',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-07-16 12:30:00',
                'delivered_time' => '2021-07-16 10:16:22',
                'total' => 715,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-07-16 10:15:33',
            ],
            [
                'full_name' => 'Halley Quine',
                'email' => 'customer2@gmail.com',
                'phone' => '0123456789',
                'address' => 'Thanh Thai, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '8',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-08-16 12:30:00',
                'delivered_time' => '2021-08-16 10:16:22',
                'total' => 615,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-08-16 10:15:33',
            ],
            [
                'full_name' => 'John Cena',
                'email' => 'customer1@gmail.com',
                'phone' => '0123456789',
                'address' => 'Dich Vong, Cau Giay, Hanoi',
                'status' => 'delivered',
                'user_id' => '7',
                'restaurant_id' => 1,
                'delivery_estimated' => '2021-09-16 12:30:00',
                'delivered_time' => '2021-09-16 10:16:22',
                'total' => 600,
                'delivered_confirm' => '1631762182.confirm-receive.jpg',
                'created_at' => '2021-09-16 10:15:33',
            ],
        ]);
        DB::table('order_details')->insert([
            [
                'order_id' => '1',
                'product_id' => '1',
                'qty' => 10,
                'user_id' => '7',
                'total' => 400,
                'created_at' => '2021-01-16 10:15:33',
            ],
            [
                'order_id' => '2',
                'product_id' => '2',
                'qty' => 10,
                'user_id' => '8',
                'total' => 350,
                'created_at' => '2021-02-16 10:15:33',
            ],
            [
                'order_id' => '3',
                'product_id' => '3',
                'qty' => 5,
                'user_id' => '8',
                'total' => 300,
                'created_at' => '2021-03-16 10:15:33',
            ],
            [
                'order_id' => '3',
                'product_id' => '4',
                'qty' => 5,
                'user_id' => '8',
                'total' => 150,
                'created_at' => '2021-03-16 10:15:33',
            ],
            [
                'order_id' => '4',
                'product_id' => '5',
                'qty' => 10,
                'user_id' => '8',
                'total' => 500,
                'created_at' => '2021-04-16 10:15:33',
            ],
            [
                'order_id' => '5',
                'product_id' => '6',
                'qty' => 15,
                'user_id' => '8',
                'total' => 525,
                'created_at' => '2021-05-16 10:15:33',
            ],
            [
                'order_id' => '6',
                'product_id' => '7',
                'qty' => 4,
                'user_id' => '8',
                'total' => 300,
                'created_at' => '2021-06-16 10:15:33',
            ],
            [
                'order_id' => '6',
                'product_id' => '8',
                'qty' => 4,
                'user_id' => '8',
                'total' => 300,
                'created_at' => '2021-06-16 10:15:33',
            ],
            [
                'order_id' => '7',
                'product_id' => '9',
                'qty' => 11,
                'user_id' => '8',
                'total' => 715,
                'created_at' => '2021-07-16 10:15:33',
            ],
            [
                'order_id' => '8',
                'product_id' => '9',
                'qty' => 6,
                'user_id' => '8',
                'total' => 390,
                'created_at' => '2021-08-16 10:15:33',
            ],
            [
                'order_id' => '8',
                'product_id' => '10',
                'qty' => 3,
                'user_id' => '8',
                'total' => 225,
                'created_at' => '2021-08-16 10:15:33',
            ],
            [
                'order_id' => '9',
                'product_id' => '3',
                'qty' => 10,
                'user_id' => '7',
                'total' => 600,
                'created_at' => '2021-09-16 10:15:33',
            ],
        ]);

        DB::table('faqs')->insert([
            [
                'title' => 'What is FoodMate ?',
                'content' => 'FoodMate is one of the most favorite e-commerce service in Vietnam, connecting millions of buyers and sellers to cater to the growing demand for online shopping a reliable e-commerce bridge, FoodMate also provides fast and convenient delivery service, giving customers the effective and optimal online shopping experience'
            ],
            [
                'title' =>'Superior delivery',
                'content' => 'The private delivery team guarantees all your food is delivered on time.'
            ],
            [
                'title' =>'Diversity foods',
                'content' => 'Thousands of products and services ranging from food, drinks, cuisines'
            ],
            [
                'title' =>'Local company',
                'content' => 'As a Vietnamese company that caters to Vietnamese people, we are knowledgeable about the Vietnamese market and know the buying psychology of our users'
            ],
        ]);
    }
}
